config/routes.rb
Rails.application.routes.draw do
  resources :outgoing_letters
  get 'dashboard/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/outgoing_letter.rb
class OutgoingLetter < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @all_outgoing_letter = OutgoingLetter.count
  end
  
  def dashboard_params
    params.require(:outgoing_letter).permit(:title, :description)
  end
end

app/controllers/outgoing_letters_controller.rb
class OutgoingLettersController < ApplicationController
  before_action :set_outgoing_letter, only: [:show, :edit, :update, :destroy]

  # GET /outgoing_letters
  # GET /outgoing_letters.json
  def index
    @outgoing_letters = OutgoingLetter.all
  end

  # GET /outgoing_letters/1
  # GET /outgoing_letters/1.json
  def show
  end

  # GET /outgoing_letters/new
  def new
    @outgoing_letter = OutgoingLetter.new
  end

  # GET /outgoing_letters/1/edit
  def edit
  end

  # POST /outgoing_letters
  # POST /outgoing_letters.json
  def create
    @outgoing_letter = OutgoingLetter.new(outgoing_letter_params)

    respond_to do |format|
      if @outgoing_letter.save
        format.html { redirect_to @outgoing_letter, notice: 'Outgoing letter was successfully created.' }
        format.json { render :show, status: :created, location: @outgoing_letter }
      else
        format.html { render :new }
        format.json { render json: @outgoing_letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outgoing_letters/1
  # PATCH/PUT /outgoing_letters/1.json
  def update
    respond_to do |format|
      if @outgoing_letter.update(outgoing_letter_params)
        format.html { redirect_to @outgoing_letter, notice: 'Outgoing letter was successfully updated.' }
        format.json { render :show, status: :ok, location: @outgoing_letter }
      else
        format.html { render :edit }
        format.json { render json: @outgoing_letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outgoing_letters/1
  # DELETE /outgoing_letters/1.json
  def destroy
    @outgoing_letter.destroy
    respond_to do |format|
      format.html { redirect_to outgoing_letters_url, notice: 'Outgoing letter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outgoing_letter
      @outgoing_letter = OutgoingLetter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outgoing_letter_params
      params.require(:outgoing_letter).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/outgoing_letters_helper.rb
module OutgoingLettersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.haml
%h1 Dashboard


.row
  .col-sm-6
    .card
      .card-body
        %h4.card-title
          Outgoing Letters
        %p.card-text
          Amount of Outgoing Letters
          = @all_outgoing_letter
        = link_to "Go to Outgoing Letters", outgoing_letters_path, class: "btn btn-primary"
  .col-sm-6
    .card
      .card-body
        %h4.card-title
          Incoming Letters
        %p.card-text
          Amount of Incoming Letters
          = @all_outgoing_letter
        = link_to "Go to Incoming Letters", outgoing_letters_path, class: "btn btn-primary"
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/outgoing_letters/_form.html.haml
= form_for @outgoing_letter do |f|
  - if @outgoing_letter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@outgoing_letter.errors.count, "error")} prohibited this outgoing_letter from being saved:"
      %ul
        - @outgoing_letter.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/outgoing_letters/edit.html.haml
%h1 Editing outgoing_letter

= render 'form'

= link_to 'Show', @outgoing_letter
\|
= link_to 'Back', outgoing_letters_path

app/views/outgoing_letters/index.html.haml
%h1 Listing outgoing_letters

%table
  %thead
    %tr
      %th Title
      %th Description
      %th
      %th
      %th

  %tbody
    - @outgoing_letters.each do |outgoing_letter|
      %tr
        %td= outgoing_letter.title
        %td= outgoing_letter.description
        %td= link_to 'Show', outgoing_letter
        %td= link_to 'Edit', edit_outgoing_letter_path(outgoing_letter)
        %td= link_to 'Destroy', outgoing_letter, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Outgoing letter', new_outgoing_letter_path

app/views/outgoing_letters/new.html.haml
%h1 New outgoing_letter

= render 'form'

= link_to 'Back', outgoing_letters_path

app/views/outgoing_letters/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @outgoing_letter.title
%p
  %b Description:
  = @outgoing_letter.description

= link_to 'Edit', edit_outgoing_letter_path(@outgoing_letter)
\|
= link_to 'Back', outgoing_letters_path

app/views/welcome/index.html.haml
.site-wrapper
  .site-wrapper-inner
    .cover-container
      .masthead.clearfix
        .inner
          %h3.masthead-brand Catat
      .inner.cover
        %h1.cover-heading Welcome to Catat
        %p.lead An app used for optimizing documentations
        %p.lead
          = link_to "Go to Dashboard", dashboard_index_path, class: "btn btn-primary btn-lg btn-block"
      .mastfoot
        .inner
          %p
            Build by
            = succeed "." do
              %a{:href => "https://github.com/fybwid"} fybwid